server:
  port: 8088
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/AdminLibraryDatabase
  application:
    name: AdminUserClient

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

