server:
  port: 8088
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/AdminLibraryDatabase
  application:
    name: eurekaToDoClient
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

